"""Knowledge pipeline service — validation + summary generation.

Step 1 (Intake & Validation) and Step 2 (Summary Generation) of the
Research Knowledge Pipeline. Pure domain logic — no I/O.

Produces a KnowledgeSummary IR from a ResearchArtifact, with validation
warnings collected for the curation gate (Step 3).
"""

from datetime import datetime
from typing import NamedTuple

from janus.models.knowledge_summary import KnowledgeSummary, TopicBlock
from janus.models.research_artifact import Finding, ResearchArtifact, Source, CONFIDENCE_LEVELS


class ValidationWarning(NamedTuple):
    """A non-fatal data quality issue detected during intake validation."""

    category: str
    message: str
    finding_index: int | None = None


class PipelineValidationError(ValueError):
    """Fatal validation error — artifact cannot proceed to summary generation."""


def validate_artifact(artifact: ResearchArtifact) -> list[ValidationWarning]:
    """Run Step 1 intake validation on a ResearchArtifact.

    Returns a list of non-fatal warnings. Raises PipelineValidationError
    on fatal schema/provenance failures.
    """
    warnings: list[ValidationWarning] = []

    # Every source must have a non-empty URL (already enforced by Source.__post_init__,
    # but double-check in case of construction bypasses).
    for i, finding in enumerate(artifact.findings):
        for j, src in enumerate(finding.sources):
            if not src.url or not src.url.strip():
                raise PipelineValidationError(
                    f"Finding {i} source {j} has empty URL"
                )

    # Freshness check: warning for future-dated accessed_at.
    now = datetime.now().astimezone()
    for i, finding in enumerate(artifact.findings):
        for j, src in enumerate(finding.sources):
            if src.accessed_at is not None and src.accessed_at > now:
                warnings.append(ValidationWarning(
                    category="freshness",
                    message=(
                        f"Finding {i} source {j} ({src.title or src.url}) "
                        f"has accessed_at in the future: {src.accessed_at.isoformat()}"
                    ),
                    finding_index=i,
                ))

    # Completeness: summary/conclusions may be empty (generated later), but warn.
    if not artifact.summary or not artifact.summary.strip():
        warnings.append(ValidationWarning(
            category="completeness",
            message="Artifact summary is empty (may be generated by pipeline)",
        ))
    if not artifact.conclusions or not artifact.conclusions.strip():
        warnings.append(ValidationWarning(
            category="completeness",
            message="Artifact conclusions is empty (may be generated by pipeline)",
        ))

    # Confidence warnings: niski findings without notes flagged for curation.
    for i, finding in enumerate(artifact.findings):
        if finding.confidence == "niski":
            warnings.append(ValidationWarning(
                category="low_confidence",
                message=(
                    f"Finding {i} (topic '{finding.topic or 'unspecified'}') "
                    f"has niski confidence: '{finding.statement}'"
                ),
                finding_index=i,
            ))

    return warnings


def generate_summary(
    artifact: ResearchArtifact,
    *,
    warnings: list[ValidationWarning] | None = None,
    explicit_entities: list[str] | None = None,
    explicit_gaps: list[str] | None = None,
) -> KnowledgeSummary:
    """Run Step 2: generate a KnowledgeSummary IR from a validated ResearchArtifact.

    Groups findings by topic, computes composite confidence per topic,
    extracts entities, identifies knowledge gaps, and orders topics.
    """
    # Group findings by topic.
    topic_findings: dict[str, list[Finding]] = {}
    for finding in artifact.findings:
        key = finding.topic or "unspecified"
        topic_findings.setdefault(key, []).append(finding)

    # Build TopicBlocks with composite confidence.
    topic_blocks = [
        TopicBlock(topic=topic, findings=findings)
        for topic, findings in topic_findings.items()
    ]

    # Generate narratives (template-based, deterministic).
    for tb in topic_blocks:
        if tb.narrative:
            continue
        n = len(tb.findings)
        parts = [f.statement for f in tb.findings]
        tb.narrative = (
            f"Based on {n} finding(s), {tb.topic} findings: "
            + ". ".join(parts) + "."
        )

    # Build the summary.
    return KnowledgeSummary(
        target=artifact.target,
        title=artifact.title,
        summary_text=artifact.summary or _generate_summary_text(artifact, topic_blocks),
        conclusions=artifact.conclusions or _generate_conclusions(artifact, topic_blocks),
        topic_blocks=topic_blocks,
        entities=explicit_entities or [],
        knowledge_gaps=explicit_gaps or [],
        artifact_version=artifact.version,
        generated_at=datetime.now().astimezone(),
    )


def _generate_summary_text(artifact: ResearchArtifact, topic_blocks: list[TopicBlock]) -> str:
    """Generate a 2-5 sentence summary from the artifact's topic blocks."""
    parts = []
    for tb in topic_blocks:
        top_findings = tb.findings[:2]
        for f in top_findings:
            parts.append(f.statement)
    if not parts:
        return artifact.summary
    return ". ".join(parts[:3]) + "."


def _generate_conclusions(artifact: ResearchArtifact, topic_blocks: list[TopicBlock]) -> str:
    """Generate key takeaways from high-confidence topics."""
    high = [tb for tb in topic_blocks if tb.composite_confidence == "wyzszy"]
    mid = [tb for tb in topic_blocks if tb.composite_confidence == "sredni"]
    parts = []
    for tb in high:
        parts.append(f"{tb.topic}: strong evidence across {len(tb.findings)} finding(s)")
    if mid:
        parts.append(f"{len(mid)} topic(s) with medium confidence need further verification")
    if not parts:
        return artifact.conclusions
    return ". ".join(parts) + "."
