"""Structured event logging helper for Janus.

Produces log envelopes conforming to the canonical observability log schema
(doc: ``docs/design/observability_log_schema.md``).

Envelope structure (top-level keys enforced by the schema):

    ts          — ISO 8601 UTC timestamp, generated by the formatter layer
    level       — lowercase log level string ("info", "warning", …)
    service     — dotted logger name (e.g. "janus.integrations.telegram")
    component   — short subsystem tag, inferred by formatter when absent
    event       — canonical dot-separated event identifier (REQUIRED)
    message     — human-readable description, strongly recommended
    data        — event-specific payload (all extra kwargs; always present)

Optional contextual fields (only included when relevant):

    trace_id         — 32-hex UUID4, generated at CLI entry, propagated down
    span_id          — short label for the emitting function boundary
    correlation_id   — application-level correlator (e.g. briefing_id)
    duration_ms      — elapsed milliseconds (float)
    error            — structured object {type, message, stack} on failure

No other top-level fields are permitted; all event-specific structured data
goes inside ``data``.

Usage in any module::

    from janus._log import emit
    import logging

    logger = logging.getLogger(__name__)

    emit(logger, "cli.command.invoked",
         trace_id=trace_id, span_id="dispatch",
         command="today", subcommand=None, pid=os.getpid())
"""

import json
import logging


def emit(
    logger: logging.Logger,
    event: str,
    *,
    trace_id: str | None = None,
    span_id: str | None = None,
    correlation_id: str | None = None,
    duration_ms: float | None = None,
    error: dict | None = None,
    level: int = logging.INFO,
    message: str = "",
    component: str | None = None,
    **data,
) -> None:
    """Emit a single structured event as an inline-JSON log message.

    The ``event`` kwarg is required — it is the canonical event name and
    becomes the ``\"event\"`` key in the JSON envelope.  All additional
    keyword arguments are merged into the ``\"data\"`` object.

    Envelope-level optional fields (``trace_id``, ``span_id``,
    ``correlation_id``, ``duration_ms``, ``error``) are only included in
    the output when they are not ``None``.  ``component`` and ``message``
    are always present — the formatter fills ``component`` with a fallback
    when the caller does not supply one.
    """
    envelope: dict = {
        "event": event,
        "message": message,
        "data": data if data else None,
    }
    if component is not None:
        envelope["component"] = component
    if trace_id is not None:
        envelope["trace_id"] = trace_id
    if span_id is not None:
        envelope["span_id"] = span_id
    if correlation_id is not None:
        envelope["correlation_id"] = correlation_id
    if duration_ms is not None:
        envelope["duration_ms"] = duration_ms
    if error is not None:
        envelope["error"] = error

    logger.log(level, json.dumps(envelope, ensure_ascii=False, default=str))
