"""Structured logging configuration for Janus.

Conforms to the canonical observability log schema
(doc: ``docs/design/observability_log_schema.md``).

Provides :func:`setup_logging` which configures the ``janus`` logger to emit
canonical-JSON log lines on stderr.  Each line is a single JSON object with
these top-level fields:

    ts        — ISO 8601 UTC timestamp (generated by the formatter layer)
    level     — lowercase logging level ("info", "warning", …)
    service   — dotted logger name
    component — short subsystem tag (falls back to logger's last segment)
    event     — canonical event name
    message   — human-readable description
    data      — event-specific payload object (or null)

Optional fields (``trace_id``, ``span_id``, ``correlation_id``,
``duration_ms``, ``error``) are passed through from :func:`janus._log.emit`
when present.

Log levels:
    * Default: WARNING and above (silent in normal operation).
    * ``--verbose`` / ``-v``: INFO and above (emits all observability events).

stdout remains untouched — only ``print()`` writes to stdout.
"""

import json
import logging
import sys
from datetime import datetime, timezone


def _level_name(record: logging.LogRecord) -> str:
    """Return the lowercase log level string for a record."""
    return record.levelname.lower()


def _component(record: logging.LogRecord) -> str:
    """Infer a short component tag from the logger name's last segment."""
    name = record.name
    if "." in name:
        return name.rsplit(".", 1)[-1]
    return name


class _StructuredFormatter(logging.Formatter):
    """Format a LogRecord as a canonical JSON line on a single stderr line.

    The ``emit`` helper writes a JSON string as the log message.  This
    formatter parses it, injects the timestamp/level/service/component
    fields that the canonical schema requires from the logging layer,
    and re-serializes.  If the message is not valid JSON (e.g. a stray
    third-party log), it wraps the text in a minimal canonical envelope.
    """

    def format(self, record: logging.LogRecord) -> str:
        envelope: dict = {}

        try:
            parsed = json.loads(record.getMessage())
            if isinstance(parsed, dict):
                envelope = parsed
            else:
                envelope = {"message": record.getMessage(), "data": None}
        except (json.JSONDecodeError, TypeError):
            envelope = {"message": record.getMessage(), "data": None}

        # Guarantee the canonical required fields that the logging layer owns.
        envelope.setdefault("ts", datetime.now(timezone.utc).isoformat())
        envelope["level"] = _level_name(record)
        envelope["service"] = record.name
        envelope.setdefault("component", _component(record))
        envelope.setdefault("message", "")
        envelope.setdefault("data", None)

        return json.dumps(envelope, ensure_ascii=False, default=str)


def setup_logging(verbose: bool = False) -> None:
    """Configure Janus logging.  Call once from ``main()`` before dispatch.

    Args:
        verbose: If True, set level to INFO (emit all observability events).
                 If False, set level to WARNING (silent in normal operation).
    """
    level = logging.INFO if verbose else logging.WARNING
    handler = logging.StreamHandler(sys.stderr)
    handler.setFormatter(_StructuredFormatter())

    root = logging.getLogger("janus")
    root.setLevel(level)
    # Remove any pre-existing handlers to avoid duplicate output on re-call.
    root.handlers.clear()
    root.addHandler(handler)
    root.propagate = False

    # Silence noisy third-party loggers.
    logging.getLogger("googleapiclient").setLevel(logging.WARNING)
    logging.getLogger("google_auth_httplib2").setLevel(logging.WARNING)
